---
title: "Simulation study"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

# Setup

```{r}
library(tidyverse)
rztpois <- function(n, lambda){
  # Zero-truncated Poisson random draws
  assertthat::assert_that(length(lambda) == 1, msg = "Only works for scalar lambda")
  x <- numeric()
  while (length(x) < n) {
    x <- c(x, rpois(n, lambda))
    x <- x[x > 0]
  }
  x[1:n]
}
dztpois <- function(x, lambda){
  # Zero-truncated Poisson density
  dpois(x, lambda) / (1 - dpois(0, lambda))
}
fitztpois <- function(x){
  # Zero-truncated Poisson MLE
  fit <- optim(mean(x), function(lambda) -sum(log(dztpois(x, lambda))), 
               hessian = TRUE, method = "BFGS")
  list(estimate = fit$par,
       se = as.numeric(sqrt(1 / fit$hessian))
  )
}
```

# Simulations

```{r}
set.seed(2022) # For reproducibility
# For each of 4 values of lambda, perform 1000 simulations of n = 100 observations
sim_study <- expand_grid(lambda = 1:4, n = 100, sim = 1:1000) %>% 
  rowwise() %>% 
  mutate(data = list(tibble(x = rztpois(n, lambda))), # Simulate data
         fit = list(fitztpois(data$x)), # Fit the MLE
         results = list(tibble( # Store the results
           method = c("MLE", "mean"),
           estimate = c(fit$estimate, mean(data$x))
         )))
sim_study
```

# Reporting a table

```{r}
sim_table <- sim_study %>% 
  select(lambda, results) %>% 
  unnest(results) %>% 
  group_by(lambda, method) %>% 
  summarise(sqrtMSE = sqrt(mean((estimate - lambda)^2)),
            se = sd(estimate),
            bias = mean(estimate - lambda),
            .groups = "drop")
sim_table
```

# Reporting a graph

```{r}
sim_table %>%  
  pivot_longer(-(lambda:method), names_to = "metric") %>% 
  ggplot(aes(x = lambda, y = value, color = method)) + geom_line()  + geom_point() + 
  facet_wrap(~metric)
```

